name: Deploy Bithollow Website (Monthly)

on:
  schedule:
    # Runs at 12:00 AM UTC on the 1st day of every month.
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, bithollow]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update docker images
        run: |
          echo "Starting monthly Bithollow deployment..."

          # cd env.${{ DEPLOY_PATH }}
          echo "Pulling latest Docker images..."
          # docker-compose -f ${{ COMPOSE_FILE }} pull

          echo "Rebuilding and restarting services with zero-downtime (if configured)..."
          # docker-compose -f $COMPOSE_FILE up -d --build --remove-orphans

          echo "Cleaning up old images and volumes..."
          # docker system prune -f

          echo "Bithollow monthly deployment complete!"
